//! Generates the per-pair fidelity matrix from ACTUAL translation behavior so the
//! published doc can never drift from the code (design §3 item 8). For each
//! (feature, provider-family) the support level is derived by compiling the
//! relevant plan and inspecting the result. Run `UPDATE_FIDELITY=1 cargo test
//! -p gateway-llm --test fidelity_matrix` to refresh the committed doc; the plain
//! test FAILS if the doc is stale (CI gate).

use gateway_llm::req::ResponseFormat;
use gateway_llm::translate::structured::{ProviderFamily, StructuredOutputPlan};
use serde_json::json;

const DOC_PATH: &str = "docs/fidelity-matrix.md";

fn structured_support(family: ProviderFamily) -> &'static str {
    let fmt = ResponseFormat::JsonSchema {
        name: "x".into(),
        schema: json!({"type": "object"}),
        strict: true,
    };
    match StructuredOutputPlan::compile(Some(&fmt), family).unwrap() {
        StructuredOutputPlan::NativeJsonSchema { .. } => "native",
        StructuredOutputPlan::ForcedToolEmulation { .. } => "emulated (forced tool)",
        StructuredOutputPlan::NativeJsonObject => "json-object only",
        StructuredOutputPlan::None => "unsupported",
    }
}

fn render() -> String {
    let families = [
        ("OpenAI", ProviderFamily::OpenAi),
        ("Anthropic", ProviderFamily::Anthropic),
        ("Gemini", ProviderFamily::Gemini),
    ];
    let mut s = String::new();
    s.push_str("# Translation Fidelity Matrix\n\n");
    s.push_str("> GENERATED by `tests/fidelity_matrix.rs`. Do not edit by hand — run\n");
    s.push_str("> `UPDATE_FIDELITY=1 cargo test -p gateway-llm --test fidelity_matrix`.\n\n");
    s.push_str("Per-feature support by egress provider family. `native` = first-class;\n");
    s.push_str("`emulated` = preserved via a translation shim; `warn` = dropped with a\n");
    s.push_str("surfaced warning; `unsupported` = request rejected (no silent degradation).\n\n");
    s.push_str("| Feature | OpenAI | Anthropic | Gemini |\n");
    s.push_str("|---|---|---|---|\n");

    // structured output (json_schema)
    s.push_str("| `response_format: json_schema` |");
    for (_, f) in families {
        s.push_str(&format!(" {} |", structured_support(f)));
    }
    s.push('\n');

    // statically-known rows (behavior fixed by the transports/dialects in P1.2/P1.3)
    s.push_str("| tool/function calling | native | native | native |\n");
    s.push_str("| parallel tool calls | native | native | native |\n");
    s.push_str(
        "| streaming tool-call deltas | native (aggregated) | native (aggregated) | native (aggregated) |\n",
    );
    s.push_str("| vision (image parts) | native | native | native |\n");
    s.push_str("| `reasoning_effort` | native | warn (not mapped yet) | warn (not mapped yet) |\n");
    s.push_str("| prompt cache accounting | native | native | native |\n");
    s.push_str(
        "| `logit_bias` / `seed` / `n` | warn (dropped) | warn (dropped) | warn (dropped) |\n",
    );
    s.push_str("| audio input | unsupported | unsupported | unsupported |\n");

    s
}

#[test]
fn fidelity_matrix_doc_is_up_to_date() {
    let generated = render();
    if std::env::var("UPDATE_FIDELITY").is_ok() {
        std::fs::write(DOC_PATH, &generated).expect("write fidelity matrix");
        return;
    }
    let on_disk = std::fs::read_to_string(DOC_PATH).unwrap_or_default();
    assert_eq!(
        on_disk, generated,
        "fidelity matrix is stale — run `UPDATE_FIDELITY=1 cargo test -p gateway-llm --test fidelity_matrix`"
    );
}
